export const OPEN_SUBMENU = "OPEN_SUBMENU";
export const CLOSE_SUBMENU = "CLOSE_SUBMENU";
export const CLOSE_SUB_SUBMENU = "CLOSE_SUB_SUBMENU";
export const OPEN_SUB_SUBMENU = "OPEN_SUB_SUBMENU";
export const OPEN_NAV_SUBMENU = "OPEN_NAV_SUBMENU";
export const CLOSE_NAV_SUBMENU = "CLOSE_NAV_SUBMENU";
